//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://infosalons.com.au/InfoServices/", ConfigurationName="Activities.ActivitiesSoap")]
    public interface ActivitiesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/FetchByActivityType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.FetchByActivityTypeResponse> FetchByActivityTypeAsync(Activities.FetchByActivityTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/FetchAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.FetchAllResponse> FetchAllAsync(Activities.FetchAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/HideRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.HideRecordResponse> HideRecordAsync(Activities.HideRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/RestoreRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.RestoreRecordResponse> RestoreRecordAsync(Activities.RestoreRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/PermanentDeleteRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.PermanentDeleteRecordResponse> PermanentDeleteRecordAsync(Activities.PermanentDeleteRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddActivity_Default", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddActivity_Default1> AddActivityAsync(Activities.AddActivity_Default request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddActivity_Gates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddActivity_Gates1> AddActivity1Async(Activities.AddActivity_Gates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddActivity_PhotoGates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddActivity_PhotoGates1> AddActivity2Async(Activities.AddActivity_PhotoGates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddPhotoActivity_GenericAddActivity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddPhotoActivity_GenericAddActivity1> AddActivity3Async(Activities.AddPhotoActivity_GenericAddActivity request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddActivity_DBMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddActivity_DBMS1> AddActivity4Async(Activities.AddActivity_DBMS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddActivity_Importing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddActivity_Importing1> AddActivity5Async(Activities.AddActivity_Importing request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddActivity_AllFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddActivity_AllFields1> AddActivity6Async(Activities.AddActivity_AllFields request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/AddtoGate_AllFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.AddtoGate_AllFields1> AddtoGateAsync(Activities.AddtoGate_AllFields request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://infosalons.com.au/InfoServices/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Activities.DeleteResponse> DeleteAsync(Activities.DeleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
    public partial class AuthenticationHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchByActivityType", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class FetchByActivityTypeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int activityType;
        
        public FetchByActivityTypeRequest()
        {
        }
        
        public FetchByActivityTypeRequest(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int activityType)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.activityType = activityType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchByActivityTypeResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class FetchByActivityTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public Activities.ArrayOfXElement FetchByActivityTypeResult;
        
        public FetchByActivityTypeResponse()
        {
        }
        
        public FetchByActivityTypeResponse(Activities.ArrayOfXElement FetchByActivityTypeResult)
        {
            this.FetchByActivityTypeResult = FetchByActivityTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchAll", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class FetchAllRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        public FetchAllRequest()
        {
        }
        
        public FetchAllRequest(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchAllResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class FetchAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public Activities.ArrayOfXElement FetchAllResult;
        
        public FetchAllResponse()
        {
        }
        
        public FetchAllResponse(Activities.ArrayOfXElement FetchAllResult)
        {
            this.FetchAllResult = FetchAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HideRecord", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class HideRecordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        public HideRecordRequest()
        {
        }
        
        public HideRecordRequest(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HideRecordResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class HideRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public int HideRecordResult;
        
        public HideRecordResponse()
        {
        }
        
        public HideRecordResponse(int HideRecordResult)
        {
            this.HideRecordResult = HideRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RestoreRecord", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class RestoreRecordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        public RestoreRecordRequest()
        {
        }
        
        public RestoreRecordRequest(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RestoreRecordResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class RestoreRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public int RestoreRecordResult;
        
        public RestoreRecordResponse()
        {
        }
        
        public RestoreRecordResponse(int RestoreRecordResult)
        {
            this.RestoreRecordResult = RestoreRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PermanentDeleteRecord", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class PermanentDeleteRecordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactkey;
        
        public PermanentDeleteRecordRequest()
        {
        }
        
        public PermanentDeleteRecordRequest(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactkey)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactkey = contactkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PermanentDeleteRecordResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class PermanentDeleteRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public int PermanentDeleteRecordResult;
        
        public PermanentDeleteRecordResponse()
        {
        }
        
        public PermanentDeleteRecordResponse(int PermanentDeleteRecordResult)
        {
            this.PermanentDeleteRecordResult = PermanentDeleteRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_Default", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_Default
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int showKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public int activityType;
        
        public AddActivity_Default()
        {
        }
        
        public AddActivity_Default(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, int activityType)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.showKey = showKey;
            this.contactKey = contactKey;
            this.activityType = activityType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_DefaultResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_Default1
    {
        
        public AddActivity_Default1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_Gates", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_Gates
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int gateKey;
        
        public AddActivity_Gates()
        {
        }
        
        public AddActivity_Gates(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey, int gateKey)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
            this.gateKey = gateKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_GatesResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_Gates1
    {
        
        public AddActivity_Gates1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_PhotoGates", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_PhotoGates
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int gateKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public bool isPhotoGate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=4)]
        public string ComputerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=5)]
        public int gatePassage;
        
        public AddActivity_PhotoGates()
        {
        }
        
        public AddActivity_PhotoGates(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey, int gateKey, bool isPhotoGate, string ComputerName, int gatePassage)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
            this.gateKey = gateKey;
            this.isPhotoGate = isPhotoGate;
            this.ComputerName = ComputerName;
            this.gatePassage = gatePassage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_PhotoGatesResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_PhotoGates1
    {
        
        public AddActivity_PhotoGates1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPhotoActivity_GenericAddActivity", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddPhotoActivity_GenericAddActivity
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int ActivityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public int showKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=4)]
        public int geteKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=5)]
        public string ComputerName;
        
        public AddPhotoActivity_GenericAddActivity()
        {
        }
        
        public AddPhotoActivity_GenericAddActivity(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey, int ActivityType, int showKey, int geteKey, string ComputerName)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
            this.ActivityType = ActivityType;
            this.showKey = showKey;
            this.geteKey = geteKey;
            this.ComputerName = ComputerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPhotoActivity_GenericAddActivityResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddPhotoActivity_GenericAddActivity1
    {
        
        public AddPhotoActivity_GenericAddActivity1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_DBMS", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_DBMS
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int showKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public int activityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=4)]
        public string activityUsername;
        
        public AddActivity_DBMS()
        {
        }
        
        public AddActivity_DBMS(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, int activityType, string activityUsername)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.showKey = showKey;
            this.contactKey = contactKey;
            this.activityType = activityType;
            this.activityUsername = activityUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_DBMSResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_DBMS1
    {
        
        public AddActivity_DBMS1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_Importing", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_Importing
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int showKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public int activityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=4)]
        public int importBatch;
        
        public AddActivity_Importing()
        {
        }
        
        public AddActivity_Importing(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, int activityType, int importBatch)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.showKey = showKey;
            this.contactKey = contactKey;
            this.activityType = activityType;
            this.importBatch = importBatch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_ImportingResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_Importing1
    {
        
        public AddActivity_Importing1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_AllFields", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_AllFields
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int showKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public int contactKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public System.DateTime activityDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=4)]
        public int gateKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=5)]
        public int activityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=6)]
        public string activityUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=7)]
        public int importBatch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=8)]
        public int syncStatus;
        
        public AddActivity_AllFields()
        {
        }
        
        public AddActivity_AllFields(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, System.DateTime activityDate, int gateKey, int activityType, string activityUsername, int importBatch, int syncStatus)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.showKey = showKey;
            this.contactKey = contactKey;
            this.activityDate = activityDate;
            this.gateKey = gateKey;
            this.activityType = activityType;
            this.activityUsername = activityUsername;
            this.importBatch = importBatch;
            this.syncStatus = syncStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActivity_AllFieldsResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddActivity_AllFields1
    {
        
        public AddActivity_AllFields1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddtoGate_AllFields", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddtoGate_AllFields
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int showKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=2)]
        public string GateNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=3)]
        public string CardNumber;
        
        public AddtoGate_AllFields()
        {
        }
        
        public AddtoGate_AllFields(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, string GateNumber, string CardNumber)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.showKey = showKey;
            this.GateNumber = GateNumber;
            this.CardNumber = CardNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddtoGate_AllFieldsResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class AddtoGate_AllFields1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public int AddtoGate_AllFieldsResult;
        
        public AddtoGate_AllFields1()
        {
        }
        
        public AddtoGate_AllFields1(int AddtoGate_AllFieldsResult)
        {
            this.AddtoGate_AllFieldsResult = AddtoGate_AllFieldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://infosalons.com.au/InfoServices/")]
        public Activities.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=0)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infosalons.com.au/InfoServices/", Order=1)]
        public int contactKey;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.connectionString = connectionString;
            this.contactKey = contactKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://infosalons.com.au/InfoServices/", IsWrapped=true)]
    public partial class DeleteResponse
    {
        
        public DeleteResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ActivitiesSoapChannel : Activities.ActivitiesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ActivitiesSoapClient : System.ServiceModel.ClientBase<Activities.ActivitiesSoap>, Activities.ActivitiesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ActivitiesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ActivitiesSoapClient.GetBindingForEndpoint(endpointConfiguration), ActivitiesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActivitiesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ActivitiesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActivitiesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ActivitiesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActivitiesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.FetchByActivityTypeResponse> Activities.ActivitiesSoap.FetchByActivityTypeAsync(Activities.FetchByActivityTypeRequest request)
        {
            return base.Channel.FetchByActivityTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.FetchByActivityTypeResponse> FetchByActivityTypeAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int activityType)
        {
            Activities.FetchByActivityTypeRequest inValue = new Activities.FetchByActivityTypeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.activityType = activityType;
            return ((Activities.ActivitiesSoap)(this)).FetchByActivityTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.FetchAllResponse> Activities.ActivitiesSoap.FetchAllAsync(Activities.FetchAllRequest request)
        {
            return base.Channel.FetchAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.FetchAllResponse> FetchAllAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            Activities.FetchAllRequest inValue = new Activities.FetchAllRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            return ((Activities.ActivitiesSoap)(this)).FetchAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.HideRecordResponse> Activities.ActivitiesSoap.HideRecordAsync(Activities.HideRecordRequest request)
        {
            return base.Channel.HideRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.HideRecordResponse> HideRecordAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            Activities.HideRecordRequest inValue = new Activities.HideRecordRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            return ((Activities.ActivitiesSoap)(this)).HideRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.RestoreRecordResponse> Activities.ActivitiesSoap.RestoreRecordAsync(Activities.RestoreRecordRequest request)
        {
            return base.Channel.RestoreRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.RestoreRecordResponse> RestoreRecordAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            Activities.RestoreRecordRequest inValue = new Activities.RestoreRecordRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            return ((Activities.ActivitiesSoap)(this)).RestoreRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.PermanentDeleteRecordResponse> Activities.ActivitiesSoap.PermanentDeleteRecordAsync(Activities.PermanentDeleteRecordRequest request)
        {
            return base.Channel.PermanentDeleteRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.PermanentDeleteRecordResponse> PermanentDeleteRecordAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactkey)
        {
            Activities.PermanentDeleteRecordRequest inValue = new Activities.PermanentDeleteRecordRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactkey = contactkey;
            return ((Activities.ActivitiesSoap)(this)).PermanentDeleteRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddActivity_Default1> Activities.ActivitiesSoap.AddActivityAsync(Activities.AddActivity_Default request)
        {
            return base.Channel.AddActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddActivity_Default1> AddActivityAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, int activityType)
        {
            Activities.AddActivity_Default inValue = new Activities.AddActivity_Default();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.showKey = showKey;
            inValue.contactKey = contactKey;
            inValue.activityType = activityType;
            return ((Activities.ActivitiesSoap)(this)).AddActivityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddActivity_Gates1> Activities.ActivitiesSoap.AddActivity1Async(Activities.AddActivity_Gates request)
        {
            return base.Channel.AddActivity1Async(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddActivity_Gates1> AddActivity1Async(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey, int gateKey)
        {
            Activities.AddActivity_Gates inValue = new Activities.AddActivity_Gates();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            inValue.gateKey = gateKey;
            return ((Activities.ActivitiesSoap)(this)).AddActivity1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddActivity_PhotoGates1> Activities.ActivitiesSoap.AddActivity2Async(Activities.AddActivity_PhotoGates request)
        {
            return base.Channel.AddActivity2Async(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddActivity_PhotoGates1> AddActivity2Async(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey, int gateKey, bool isPhotoGate, string ComputerName, int gatePassage)
        {
            Activities.AddActivity_PhotoGates inValue = new Activities.AddActivity_PhotoGates();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            inValue.gateKey = gateKey;
            inValue.isPhotoGate = isPhotoGate;
            inValue.ComputerName = ComputerName;
            inValue.gatePassage = gatePassage;
            return ((Activities.ActivitiesSoap)(this)).AddActivity2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddPhotoActivity_GenericAddActivity1> Activities.ActivitiesSoap.AddActivity3Async(Activities.AddPhotoActivity_GenericAddActivity request)
        {
            return base.Channel.AddActivity3Async(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddPhotoActivity_GenericAddActivity1> AddActivity3Async(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey, int ActivityType, int showKey, int geteKey, string ComputerName)
        {
            Activities.AddPhotoActivity_GenericAddActivity inValue = new Activities.AddPhotoActivity_GenericAddActivity();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            inValue.ActivityType = ActivityType;
            inValue.showKey = showKey;
            inValue.geteKey = geteKey;
            inValue.ComputerName = ComputerName;
            return ((Activities.ActivitiesSoap)(this)).AddActivity3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddActivity_DBMS1> Activities.ActivitiesSoap.AddActivity4Async(Activities.AddActivity_DBMS request)
        {
            return base.Channel.AddActivity4Async(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddActivity_DBMS1> AddActivity4Async(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, int activityType, string activityUsername)
        {
            Activities.AddActivity_DBMS inValue = new Activities.AddActivity_DBMS();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.showKey = showKey;
            inValue.contactKey = contactKey;
            inValue.activityType = activityType;
            inValue.activityUsername = activityUsername;
            return ((Activities.ActivitiesSoap)(this)).AddActivity4Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddActivity_Importing1> Activities.ActivitiesSoap.AddActivity5Async(Activities.AddActivity_Importing request)
        {
            return base.Channel.AddActivity5Async(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddActivity_Importing1> AddActivity5Async(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, int activityType, int importBatch)
        {
            Activities.AddActivity_Importing inValue = new Activities.AddActivity_Importing();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.showKey = showKey;
            inValue.contactKey = contactKey;
            inValue.activityType = activityType;
            inValue.importBatch = importBatch;
            return ((Activities.ActivitiesSoap)(this)).AddActivity5Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddActivity_AllFields1> Activities.ActivitiesSoap.AddActivity6Async(Activities.AddActivity_AllFields request)
        {
            return base.Channel.AddActivity6Async(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddActivity_AllFields1> AddActivity6Async(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, int contactKey, System.DateTime activityDate, int gateKey, int activityType, string activityUsername, int importBatch, int syncStatus)
        {
            Activities.AddActivity_AllFields inValue = new Activities.AddActivity_AllFields();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.showKey = showKey;
            inValue.contactKey = contactKey;
            inValue.activityDate = activityDate;
            inValue.gateKey = gateKey;
            inValue.activityType = activityType;
            inValue.activityUsername = activityUsername;
            inValue.importBatch = importBatch;
            inValue.syncStatus = syncStatus;
            return ((Activities.ActivitiesSoap)(this)).AddActivity6Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.AddtoGate_AllFields1> Activities.ActivitiesSoap.AddtoGateAsync(Activities.AddtoGate_AllFields request)
        {
            return base.Channel.AddtoGateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.AddtoGate_AllFields1> AddtoGateAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int showKey, string GateNumber, string CardNumber)
        {
            Activities.AddtoGate_AllFields inValue = new Activities.AddtoGate_AllFields();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.showKey = showKey;
            inValue.GateNumber = GateNumber;
            inValue.CardNumber = CardNumber;
            return ((Activities.ActivitiesSoap)(this)).AddtoGateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Activities.DeleteResponse> Activities.ActivitiesSoap.DeleteAsync(Activities.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Activities.DeleteResponse> DeleteAsync(Activities.AuthenticationHeader AuthenticationHeader, string connectionString, int contactKey)
        {
            Activities.DeleteRequest inValue = new Activities.DeleteRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.connectionString = connectionString;
            inValue.contactKey = contactKey;
            return ((Activities.ActivitiesSoap)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActivitiesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ActivitiesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActivitiesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cloud01.infosalons.com.au/beta/InfoServices/InfoWeb/Activities.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ActivitiesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cloud01.infosalons.com.au/beta/InfoServices/InfoWeb/Activities.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ActivitiesSoap,
            
            ActivitiesSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.1")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
